# Generated by Django 4.2.7 on 2024-09-16 18:17

import Aplicaciones.Secuencias.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Protocolo_Metodos", "0002_muestras_y_placebos_unique_intro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Protocolo_Muestras", "0002_rename_viabilidad_viabilidadproceso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invalidar_Secuencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon",
                    models.CharField(max_length=250, null=True, verbose_name="Causa"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=250, null=True, verbose_name="Sistema"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_validar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_invalidar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_impresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secuencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_Invalidez",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="Fecha ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, verbose_name="Nombre")),
                ("fecha_Inicio", models.DateTimeField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_Final",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Registrada", "REGISTRADA"),
                            ("Invalida", "INVALIDA"),
                            ("Revisada", "REVISADA"),
                            ("Impresa", "IMPRESA"),
                            ("Reportada", "REPORTADA"),
                            ("Auditada", "AUDITADA"),
                            ("Ensayo", "ENSAYO"),
                        ],
                        default="Registrada",
                        max_length=90,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        null=True,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_invalidar",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Invalidéz"
                    ),
                ),
                (
                    "fecha_validar",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Validación"
                    ),
                ),
                (
                    "fecha_impresion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Impresión"
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Reporte"
                    ),
                ),
                (
                    "fecha_auditada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha auditada"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        default=Aplicaciones.Secuencias.models.Secuencias.individual,
                        max_length=250,
                        null=True,
                        verbose_name="Referencia Reporte",
                    ),
                ),
                (
                    "auditar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_auditor",
                        verbose_name="Auditada por",
                    ),
                ),
                (
                    "imprimir",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_impresion",
                        verbose_name="Impresa por",
                    ),
                ),
                (
                    "invalidar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_invalidar",
                        verbose_name="Invalidada por",
                    ),
                ),
                (
                    "invalidez",
                    models.ForeignKey(
                        blank=True,
                        default="N.A",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.invalidar_secuencia",
                        verbose_name="Invalidar",
                    ),
                ),
                (
                    "metodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.metodo",
                        verbose_name="Metodo",
                    ),
                ),
                (
                    "muestras",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.muestras_y_placebos",
                        verbose_name="Muestras",
                    ),
                ),
                (
                    "parametro_sq",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.parametro",
                        verbose_name="Parametro",
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.protocolos",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "protocolo_proceso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Muestras.proceso",
                        verbose_name="Protocolo de Proceso",
                    ),
                ),
                (
                    "reportar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_reporte",
                        verbose_name="Reportada por",
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.sistema",
                        verbose_name="Sistema",
                    ),
                ),
                (
                    "validar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_validar",
                        verbose_name="Validada por",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=(
                    "protocolo_proceso",
                    "muestras",
                    "fecha_Invalidez",
                    "parametro_sq",
                    "protocolo",
                ),
                name="unique_intro_nue",
            ),
        ),
    ]
