# Generated by Django 4.2.7 on 2024-06-12 16:51

import Aplicaciones.Secuencias.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invalidar_Secuencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon",
                    models.CharField(max_length=250, null=True, verbose_name="Sistema"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=250, null=True, verbose_name="Sistema"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_impresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario_auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secuencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, verbose_name="Nombre")),
                ("fecha_Inicio", models.DateTimeField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_Final",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Registrada", "REGISTRADA"),
                            ("Invalida", "INVALIDA"),
                            ("Revisada", "REVISADA"),
                            ("Impresa", "IMPRESA"),
                            ("Reportada", "REPORTADA"),
                            ("Auditada", "AUDITADA"),
                        ],
                        default="Registrada",
                        max_length=90,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        null=True,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_impresion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Impresión"
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Reporte"
                    ),
                ),
                (
                    "fecha_auditada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha auditada"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        default=Aplicaciones.Secuencias.models.Secuencias.individual,
                        max_length=250,
                        null=True,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "auditar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_auditor",
                        verbose_name="Auditar",
                    ),
                ),
                (
                    "imprimir",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario1",
                        verbose_name="Imprimir",
                    ),
                ),
                (
                    "invalidez",
                    models.ForeignKey(
                        blank=True,
                        default="N.A",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.invalidar_secuencia",
                        verbose_name="Invalidar",
                    ),
                ),
                (
                    "parametro_sq",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.parametro",
                        verbose_name="Parametro",
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.protocolos",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "reportar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.usuario_impresion",
                        verbose_name="Reportar",
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secuencias.sistema",
                        verbose_name="Sistema",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo", "parametro_sq", "status"), name="unique_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", 1)),
                fields=("protocolo", "parametro_sq"),
                name="unique_2",
            ),
        ),
    ]
