# Generated by Django 4.2.7 on 2024-09-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="secuencias", unique_together=set(),),
    ]
