# Generated by Django 4.2.7 on 2024-08-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0135_etapa_ensayo"),
        ("Protocolo_Muestras", "0001_initial"),
        ("Secuencias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencias",
            name="muestras",
            field=models.ManyToManyField(to="Protocolo_Metodos.muestras_y_placebos"),
        ),
        migrations.AddField(
            model_name="secuencias",
            name="protocolo_proceso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Muestras.proceso",
                verbose_name="Protocolo de Proceso",
            ),
        ),
    ]
