# Generated by Django 4.2.7 on 2024-09-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0001_initial"),
        ("Protocolo_Muestras", "0001_initial"),
        ("Secuencias", "0002_alter_secuencias_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="parametro_sq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="protocolo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.protocolos",
                verbose_name="Protocolo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secuencias",
            unique_together={("protocolo_proceso", "muestras", "fecha_Invalidez")},
        ),
    ]
