# Generated by Django 4.2.7 on 2024-08-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0137_alter_muestras_y_placebos_etapa_and_more"),
        ("Secuencias", "0002_secuencias_muestras_secuencias_protocolo_proceso"),
    ]

    operations = [
        migrations.RemoveField(model_name="secuencias", name="muestras",),
        migrations.AddField(
            model_name="secuencias",
            name="muestras",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.muestras_y_placebos",
                verbose_name="Muestras",
            ),
        ),
    ]
