# Generated by Django 4.2.7 on 2024-08-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Muestras", "0002_alter_proceso_estado_del_proceso_and_more"),
        ("Protocolo_Metodos", "0137_alter_muestras_y_placebos_etapa_and_more"),
        ("Secuencias", "0003_remove_secuencias_muestras_secuencias_muestras"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="secuencias",
            unique_together={
                ("protocolo_proceso", "muestras", "fecha_Invalidez", "parametro_sq")
            },
        ),
    ]
