# Generated by Django 4.2.7 on 2024-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0004_alter_secuencias_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo", "parametro_sq", "fecha_Invalidez"),
                name="unique_intro",
            ),
        ),
    ]
