# Generated by Django 4.2.7 on 2024-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0004_remove_secuencias_unique_1_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="secuencias", name="unique_undeleted_name",
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo", "parametro_sq"), name="unique_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", 0)),
                fields=("protocolo", "parametro_sq"),
                name="unique_2",
            ),
        ),
    ]
