# Generated by Django 4.2.7 on 2024-08-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0138_metodo"),
        ("Secuencias", "0004_alter_secuencias_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencias",
            name="metodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodo",
                verbose_name="Metodo",
            ),
        ),
    ]
