# Generated by Django 4.2.7 on 2024-09-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0006_secuencias_unique_intro1"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro1",),
    ]
