# Generated by Django 4.2.7 on 2024-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0007_remove_secuencias_unique_intro1"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo_proceso", "muestras", "fecha_Invalidez"),
                name="unique_intro_nue",
            ),
        ),
    ]
