# Generated by Django 4.2.7 on 2024-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0007_remove_secuencias_unique_2_secuencias_unique_2"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_2",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo", "parametro_sq", "status"), name="unique_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", 0)),
                fields=("protocolo", "parametro_sq"),
                name="unique_2",
            ),
        ),
    ]
