# Generated by Django 4.2.7 on 2024-09-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0008_secuencias_unique_intro_nue"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro_nue",),
    ]
