# Generated by Django 4.2.7 on 2024-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0009_remove_secuencias_unique_2_secuencias_unique_2"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_2",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Status.REGISTRADA")),
                fields=("protocolo", "parametro_sq", "status"),
                name="unique_2",
            ),
        ),
    ]
