# Generated by Django 4.2.7 on 2024-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0009_remove_secuencias_unique_intro_nue"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo_proceso", "muestras", "fecha_Invalidez"),
                name="unique_intro_nue",
            ),
        ),
    ]
