# Generated by Django 4.2.7 on 2024-06-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
        ("Secuencias", "0010_remove_secuencias_unique_2_secuencias_unique_2"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_1",),
        migrations.RemoveConstraint(model_name="secuencias", name="unique_2",),
        migrations.AlterUniqueTogether(
            name="secuencias", unique_together={("protocolo", "parametro_sq")},
        ),
    ]
