# Generated by Django 4.2.7 on 2024-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0011_remove_secuencias_unique_intro_nue_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro_nue",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=(
                    "protocolo_proceso",
                    "muestras",
                    "fecha_Invalidez",
                    "parametro_sq",
                    "protocolo",
                ),
                name="unique_intro_nue",
            ),
        ),
    ]
