# Generated by Django 4.2.7 on 2024-06-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0011_remove_secuencias_unique_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(default=True),
        ),
    ]
