# Generated by Django 4.2.7 on 2024-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0012_secuencias_order_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="secuencias", name="id",),
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
