# Generated by Django 4.2.7 on 2024-06-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0013_remove_secuencias_id_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencias",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True),
        ),
    ]
