# Generated by Django 4.2.7 on 2024-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0014_secuencias_id_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
