# Generated by Django 4.2.7 on 2024-06-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
        ("Secuencias", "0015_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="secuencias",
            unique_together={("protocolo", "parametro_sq", "order_number")},
        ),
    ]
