# Generated by Django 4.2.7 on 2024-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0016_alter_secuencias_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
