# Generated by Django 4.2.7 on 2024-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
        ("Secuencias", "0018_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="secuencias", unique_together={("protocolo", "parametro_sq")},
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
