# Generated by Django 4.2.7 on 2024-06-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
        ("Secuencias", "0019_alter_secuencias_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="secuencias", unique_together=set(),),
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="secuencias",
            unique_together={("protocolo", "parametro_sq", "order_number")},
        ),
    ]
