# Generated by Django 4.2.7 on 2024-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0020_alter_secuencias_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
