# Generated by Django 4.2.7 on 2024-06-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0022_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="order_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
