# Generated by Django 4.2.7 on 2024-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
        ("Secuencias", "0023_alter_secuencias_order_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="secuencias", unique_together=set(),),
        migrations.AddField(
            model_name="secuencias",
            name="fecha_Invalidez",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Invalidez"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secuencias",
            unique_together={("protocolo", "parametro_sq", "fecha_Invalidez")},
        ),
        migrations.RemoveField(model_name="secuencias", name="order_number",),
    ]
