# Generated by Django 4.2.7 on 2024-06-18 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0024_alter_secuencias_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_Invalidez",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Fecha de Invalidez",
            ),
        ),
    ]
