# Generated by Django 4.2.7 on 2024-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0025_alter_secuencias_fecha_invalidez"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_Invalidez",
            field=models.DateTimeField(
                blank=True,
                default="2024-01-01",
                null=True,
                verbose_name="Fecha de Invalidez",
            ),
        ),
    ]
