# Generated by Django 4.2.7 on 2024-06-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0027_alter_secuencias_fecha_invalidez"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidar_secuencia",
            name="razon",
            field=models.CharField(max_length=250, null=True, verbose_name="Causa"),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="auditar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Secuencias.usuario_auditor",
                verbose_name="Auditada por",
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="imprimir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Secuencias.usuario1",
                verbose_name="Impresa por",
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="reportar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Secuencias.usuario_impresion",
                verbose_name="Reportada por",
            ),
        ),
    ]
