# Generated by Django 4.2.7 on 2024-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0029_alter_secuencias_fecha_auditada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_auditada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha auditada"
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_impresion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Impresión"
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_reporte",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Reporte"
            ),
        ),
    ]
