# Generated by Django 4.2.7 on 2024-07-05 14:07

import Aplicaciones.Secuencias.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0030_alter_secuencias_fecha_auditada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="fecha_Invalidez",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Fecha ID",
            ),
        ),
        migrations.AlterField(
            model_name="secuencias",
            name="referencia",
            field=models.CharField(
                blank=True,
                default=Aplicaciones.Secuencias.models.Secuencias.individual,
                max_length=250,
                null=True,
                verbose_name="Referencia Reporte",
            ),
        ),
    ]
