# Generated by Django 4.2.7 on 2024-07-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Secuencias", "0031_alter_secuencias_fecha_invalidez_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="usuario1", new_name="usuario_reporte",),
        migrations.AlterField(
            model_name="secuencias",
            name="imprimir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Secuencias.usuario_impresion",
                verbose_name="Impresa por",
            ),
        ),
    ]
