# Generated by Django 4.2.7 on 2024-09-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Muestras", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Viabilidad", new_name="ViabilidadProceso",),
    ]
