# Generated by Django 4.2.7 on 2024-08-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0137_alter_muestras_y_placebos_etapa_and_more"),
        ("Protocolo_Muestras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceso",
            name="estado_del_proceso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.estadoprotocolo",
                verbose_name="Estado del proceso",
            ),
        ),
        migrations.DeleteModel(name="Estado_Proceso",),
    ]
