# Generated by Django 4.2.7 on 2024-08-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0139_protocolos_metodo"),
        ("Protocolo_Muestras", "0003_proceso_metodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceso",
            name="metodologia",
            field=models.ForeignKey(
                max_length=90,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
        ),
    ]
