# Generated by Django 4.2.1 on 2023-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parametro",
                    models.CharField(max_length=90, verbose_name="Parametros"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(max_length=250, verbose_name="Observaciones"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subparametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subparametro",
                    models.CharField(max_length=90, verbose_name="Parametros"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(max_length=250, verbose_name="Observaciones"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protocolos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(verbose_name="Fecha de Registro"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=90, verbose_name="Código Protocolo"),
                ),
                (
                    "nombrre",
                    models.TextField(
                        max_length=250, verbose_name="Nombre del Protocolo"
                    ),
                ),
                ("ensayo", models.CharField(max_length=90, verbose_name="Ensayo")),
                ("muestra", models.TextField(max_length=250, verbose_name="Muestras")),
                (
                    "metodologia",
                    models.CharField(
                        choices=[
                            ("HPLC Ó UHPLC", "HPLC_UHPLC"),
                            ("HPLC", "HPLC"),
                            ("UHPLC", "UHPLC"),
                        ],
                        default="HPLC Ó UHPLC",
                        max_length=90,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Inactivo", "INACTIVO"),
                            ("En Ejecución", "EJECUCION"),
                            ("En revisión", "REVISION"),
                            ("finalizado", "FINALIZADO"),
                            ("Entregado", "ENTREGADO"),
                        ],
                        default="Inactivo",
                        max_length=90,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(max_length=250, verbose_name="Observaciones"),
                ),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Protocolo_Metodos.parametro",
                        verbose_name="Parámetros",
                    ),
                ),
            ],
        ),
    ]
