# Generated by Django 4.2.7 on 2024-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="muestras_y_placebos",
            constraint=models.UniqueConstraint(
                fields=("lote_muestra", "etapa"), name="unique_intro"
            ),
        ),
    ]
