# Generated by Django 4.2.1 on 2023-08-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="parametro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Parámetros",
            ),
        ),
        migrations.AlterField(
            model_name="subparametro",
            name="subparametro",
            field=models.CharField(max_length=90, verbose_name="Subparametros"),
        ),
    ]
