# Generated by Django 4.2.1 on 2023-08-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0002_alter_parametro_parametro_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="parametro",),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Parámetros",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="parametro",
            field=models.ManyToManyField(
                to="Protocolo_Metodos.subparametro", verbose_name="Parámetros"
            ),
        ),
    ]
