# Generated by Django 4.2.7 on 2024-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0002_muestras_y_placebos_unique_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapa",
            name="nombre_etapa",
            field=models.CharField(max_length=90, verbose_name="Etapa"),
        ),
        migrations.AddConstraint(
            model_name="etapa",
            constraint=models.UniqueConstraint(
                fields=("nombre_etapa", "ensayo"), name="etapa"
            ),
        ),
    ]
