# Generated by Django 4.2.1 on 2023-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0003_remove_parametro_parametro_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                to="Protocolo_Metodos.subparametro", verbose_name="Parámetros"
            ),
        ),
    ]
