# Generated by Django 4.2.1 on 2023-08-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0004_remove_protocolos_parametro_protocolos_parametro"),
    ]

    operations = [
        migrations.DeleteModel(name="Parametro",),
    ]
