# Generated by Django 4.2.1 on 2023-08-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0005_delete_parametro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(max_length=250, verbose_name="Observaciones"),
                ),
                (
                    "parametro",
                    models.ManyToManyField(
                        to="Protocolo_Metodos.subparametro", verbose_name="Parámetros"
                    ),
                ),
            ],
        ),
    ]
