# Generated by Django 4.2.1 on 2023-08-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0006_parametro"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="parametro",),
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="parametro",
            name="parametro",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Parámetros",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Parámetros",
            ),
            preserve_default=False,
        ),
    ]
