# Generated by Django 4.2.1 on 2023-08-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0007_remove_parametro_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="parametro",
            field=models.CharField(max_length=90, verbose_name="Subparametros"),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
        ),
        migrations.DeleteModel(name="Subparametro",),
    ]
