# Generated by Django 4.2.1 on 2023-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0010_alter_parametro_parametro_alter_protocolos_parametro",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro", old_name="parametro", new_name="subparametro",
        ),
    ]
