# Generated by Django 4.2.1 on 2023-08-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0011_rename_parametro_parametro_subparametro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="protocolos", old_name="nombrre", new_name="nombre",
        ),
    ]
