# Generated by Django 4.2.1 on 2023-08-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0012_rename_nombrre_protocolos_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro", old_name="subparametro", new_name="parametro",
        ),
    ]
