# Generated by Django 4.2.1 on 2023-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0013_rename_subparametro_parametro_parametro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro", old_name="parametro", new_name="nombre",
        ),
        migrations.RemoveField(model_name="parametro", name="observaciones",),
        migrations.AddField(
            model_name="parametro",
            name="subparametro",
            field=models.CharField(
                default=None, max_length=250, verbose_name="subparametro"
            ),
            preserve_default=False,
        ),
    ]
