# Generated by Django 4.2.1 on 2023-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0014_rename_parametro_parametro_nombre_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                to="Protocolo_Metodos.parametro", verbose_name="Parámetros"
            ),
        ),
    ]
