# Generated by Django 4.2.1 on 2023-08-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0015_remove_protocolos_parametro_protocolos_parametro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subparametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=90,
                        null=True,
                        verbose_name="Subparametros",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="parametros"
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="subparametro",
            field=models.ForeignKey(
                max_length=250,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="subparametro",
            ),
        ),
    ]
