# Generated by Django 4.2.1 on 2023-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0016_subparametro_alter_parametro_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre",
            field=models.CharField(
                default=None, max_length=90, verbose_name="parametros"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subparametro",
            name="nombre",
            field=models.CharField(
                default=None, max_length=90, verbose_name="Subparametros"
            ),
            preserve_default=False,
        ),
    ]
