# Generated by Django 4.2.1 on 2023-08-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0018_remove_parametro_subparametro_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="subparametro",),
        migrations.AddField(
            model_name="parametro",
            name="subparametro",
            field=models.OneToOneField(
                default=None,
                max_length=250,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="subparametro",
            ),
            preserve_default=False,
        ),
    ]
