# Generated by Django 4.2.1 on 2023-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0019_remove_parametro_subparametro_parametro_subparametro",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                max_length=90,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
        ),
    ]
