# Generated by Django 4.2.1 on 2023-08-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0024_remove_protocolos_parametro_protocolos_parametro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subparametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=90, verbose_name="parametros")),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="parametro", name="subparametro",),
        migrations.RemoveField(model_name="parametro", name="nombre",),
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="parametro",
            name="nombre",
            field=models.ManyToManyField(
                max_length=90,
                to="Protocolo_Metodos.subparametro",
                verbose_name="parametros",
            ),
        ),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                default=None,
                max_length=90,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
            preserve_default=False,
        ),
    ]
