# Generated by Django 4.2.1 on 2023-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0028_alter_protocolos_fecha_registro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subparametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=90, verbose_name="subparametros"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="parametro", name="subparametro",),
        migrations.RemoveField(model_name="parametro", name="nombre",),
        migrations.AddField(
            model_name="parametro",
            name="nombre",
            field=models.ManyToManyField(
                max_length=90,
                to="Protocolo_Metodos.subparametro",
                verbose_name="parametros",
            ),
        ),
    ]
