# Generated by Django 4.2.1 on 2023-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0029_subparametro_remove_parametro_subparametro_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="nombre",),
        migrations.DeleteModel(name="Subparametro",),
        migrations.AddField(
            model_name="parametro",
            name="nombre",
            field=models.CharField(
                default=None, max_length=90, verbose_name="parametros"
            ),
            preserve_default=False,
        ),
    ]
