# Generated by Django 4.2.1 on 2023-08-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0030_remove_parametro_nombre_delete_subparametro_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro", old_name="nombre", new_name="parametro",
        ),
    ]
