# Generated by Django 4.2.1 on 2023-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0031_rename_nombre_parametro_parametro"),
    ]

    operations = [
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                max_length=90,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
        ),
    ]
