# Generated by Django 4.2.1 on 2023-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0032_remove_protocolos_parametro_protocolos_parametro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default=False,
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Inactivo", "INACTIVO"),
                    ("En Ejecución", "EJECUCION"),
                    ("En revisión", "REVISION"),
                    ("finalizado", "FINALIZADO"),
                    ("Entregado", "ENTREGADO"),
                ],
                default=False,
                max_length=90,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.CharField(
                choices=[
                    ("HPLC Ó UHPLC", "HPLC_UHPLC"),
                    ("HPLC", "HPLC"),
                    ("UHPLC", "UHPLC"),
                ],
                default=False,
                max_length=90,
                verbose_name="metodologia",
            ),
        ),
    ]
