# Generated by Django 4.2.1 on 2023-08-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0033_alter_parametro_condicion_alter_protocolos_estado_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro", old_name="parametro", new_name="nombre",
        ),
    ]
