# Generated by Django 4.2.1 on 2023-08-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0034_rename_parametro_parametro_nombre"),
    ]

    operations = [
        migrations.RemoveField(model_name="protocolos", name="parametro",),
        migrations.AddField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                default=None,
                max_length=90,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
            preserve_default=False,
        ),
    ]
