# Generated by Django 4.2.1 on 2023-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0040_alter_protocolos_fecha_registro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_registro",
            field=models.DateField(
                blank=True,
                help_text="AAAA/MM/DD",
                null=True,
                verbose_name="Fecha de Registro",
            ),
        ),
    ]
