# Generated by Django 4.2.1 on 2023-08-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0045_alter_protocolos_metodologia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                default=None,
                max_length=90,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                default=None,
                max_length=90,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="Parámetros",
            ),
            preserve_default=False,
        ),
    ]
