# Generated by Django 4.2.1 on 2023-08-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0046_alter_protocolos_metodologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
            ),
        ),
    ]
