# Generated by Django 4.2.1 on 2023-08-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0047_alter_protocolos_metodologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metodologia",
            name="nombre",
            field=models.CharField(max_length=90, verbose_name="Metodologia"),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre",
            field=models.CharField(max_length=90, verbose_name="Parametros"),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="parametro",
            ),
        ),
    ]
