# Generated by Django 4.2.1 on 2023-08-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0049_remove_metodologia_condicion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metodologia",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default=False,
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default=False,
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
    ]
