# Generated by Django 4.2.1 on 2023-08-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0050_metodologia_condicion_parametro_condicion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocolo_metodologia",
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocolo_parametro",
                to="Protocolo_Metodos.parametro",
                verbose_name="parametro",
            ),
        ),
    ]
