# Generated by Django 4.2.1 on 2023-08-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0051_alter_protocolos_metodologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="nombre",
            field=models.CharField(max_length=250, verbose_name="Nombre del Protocolo"),
        ),
    ]
