# Generated by Django 4.2.1 on 2023-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0053_alter_protocolos_metodologia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metodologia", old_name="nombre", new_name="nombre_metodologia",
        ),
        migrations.RemoveField(model_name="parametro", name="nombre",),
        migrations.AddField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.CharField(
                default=None, max_length=90, verbose_name="Nombre Parametros"
            ),
            preserve_default=False,
        ),
    ]
