# Generated by Django 4.2.1 on 2023-08-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0054_rename_nombre_metodologia_nombre_metodologia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Protocolo_Metodos.parametro",
                verbose_name="parametro",
            ),
        ),
    ]
