# Generated by Django 4.2.1 on 2023-08-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0055_alter_protocolos_metodologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metodologia",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="metodologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodologia",
                verbose_name="metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="parametro",
            ),
        ),
    ]
