# Generated by Django 4.2.1 on 2023-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0058_alter_metodologia_nombre_metodologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metodologia",
            name="nombre_metodologia",
            field=models.IntegerField(verbose_name="Metodologia"),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.IntegerField(verbose_name="Nombre Parametros"),
        ),
    ]
