# Generated by Django 4.2.1 on 2023-08-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0063_alter_metodologia_id_alter_parametro_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.OneToOneField(
                max_length=90,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.parametro",
                verbose_name="parametro",
            ),
        ),
    ]
