# Generated by Django 4.2.1 on 2023-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0065_remove_protocolos_parametro_protocolos_parametro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(to="Protocolo_Metodos.parametro"),
        ),
    ]
