# Generated by Django 4.2.1 on 2023-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0066_alter_protocolos_parametro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                to="Protocolo_Metodos.parametro", verbose_name="hello"
            ),
        ),
    ]
