# Generated by Django 4.2.1 on 2023-08-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0067_alter_protocolos_parametro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(to="Protocolo_Metodos.parametro"),
        ),
    ]
