# Generated by Django 4.2.1 on 2023-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0069_estadoprotocolo_remove_protocolos_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_registro",
            field=models.DateField(
                auto_created=True,
                auto_now_add=True,
                help_text="AAAA/MM/DD",
                verbose_name="Fecha de Registro",
            ),
        ),
    ]
