# Generated by Django 4.2.1 on 2023-08-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0070_alter_protocolos_fecha_registro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ensayo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_ensayo",
                    models.CharField(max_length=90, verbose_name="Ensayo"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default=False,
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="ensayo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.ensayo",
                verbose_name="Ensayo",
            ),
        ),
    ]
