# Generated by Django 4.2.1 on 2023-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0071_ensayo_alter_protocolos_ensayo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_viabilidad",
                    models.CharField(max_length=90, verbose_name="Nombre Viabilidad"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default=False,
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="protocolos", old_name="muestra", new_name="muestras_y_Placebos",
        ),
        migrations.AddField(
            model_name="protocolos",
            name="viabilidad",
            field=models.ManyToManyField(to="Protocolo_Metodos.viabilidad"),
        ),
    ]
