# Generated by Django 4.2.1 on 2023-09-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0072_viabilidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.CharField(
                default=None, max_length=90, verbose_name="Nombre Parametros Titulo"
            ),
            preserve_default=False,
        ),
    ]
