# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0073_parametro_nombre_titulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subparametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_subparametro",
                    models.CharField(max_length=90, verbose_name="Subparametro"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="parametro", name="nombre_parametro",),
        migrations.AddField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ManyToManyField(to="Protocolo_Metodos.subparametro"),
        ),
    ]
