# Generated by Django 4.2.1 on 2023-09-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0074_subparametro_remove_parametro_nombre_parametro_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(blank=True, to="Protocolo_Metodos.parametro"),
        ),
    ]
