# Generated by Django 4.2.1 on 2023-09-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0075_alter_protocolos_parametro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ManyToManyField(
                blank=True, to="Protocolo_Metodos.subparametro"
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="Nombre Parametros Titulo"
            ),
        ),
        migrations.AlterField(
            model_name="subparametro",
            name="nombre_subparametro",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="Subparametro"
            ),
        ),
    ]
