# Generated by Django 4.2.1 on 2023-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0076_alter_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ManyToManyField(
                blank=True,
                related_name="nombre_parametro",
                to="Protocolo_Metodos.subparametro",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                blank=True, related_name="parametro", to="Protocolo_Metodos.parametro"
            ),
        ),
    ]
