# Generated by Django 4.2.1 on 2023-09-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0077_alter_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Titulo_Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_parametro",
                    models.CharField(
                        blank=True, max_length=90, verbose_name="titulo_parametro"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.titulo_parametro",
                verbose_name="Titulo_Parametro",
            ),
        ),
    ]
