# Generated by Django 4.2.1 on 2023-09-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0078_titulo_parametro_alter_parametro_nombre_titulo"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="nombre_parametro",),
        migrations.AddField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
            ),
            preserve_default=False,
        ),
    ]
