# Generated by Django 4.2.1 on 2023-09-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0079_remove_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="nombre_parametro",),
        migrations.AddField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ManyToManyField(
                blank=True, to="Protocolo_Metodos.subparametro"
            ),
        ),
    ]
