# Generated by Django 4.2.1 on 2023-09-23 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0080_remove_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ManyToManyField(
                blank=True,
                related_name="parametro",
                to="Protocolo_Metodos.subparametro",
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parametro",
                to="Protocolo_Metodos.titulo_parametro",
                verbose_name="Titulo_Parametro",
            ),
        ),
    ]
