# Generated by Django 4.2.1 on 2023-09-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0082_alter_protocolos_parametro"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="nombre_parametro",),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.titulo_parametro",
                verbose_name="Titulo_Parametro",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Titulo_Parametro",
            ),
        ),
    ]
