# Generated by Django 4.2.1 on 2023-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0083_remove_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Muestras_y_Placebos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_muestra_interno",
                    models.CharField(max_length=90, verbose_name="CIM / LIMS"),
                ),
                (
                    "codigo_muestra_producto",
                    models.CharField(max_length=90, verbose_name="Código de Producto"),
                ),
                ("lote_muestra", models.CharField(max_length=90, verbose_name="Lote")),
                (
                    "observaciones_muestras",
                    models.TextField(max_length=300, verbose_name="Observaciones"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default=False,
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="protocolos", name="muestras_y_Placebos",),
        migrations.AddField(
            model_name="protocolos",
            name="muestras_y_Placebos",
            field=models.ManyToManyField(to="Protocolo_Metodos.muestras_y_placebos"),
        ),
    ]
