# Generated by Django 4.2.1 on 2023-10-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0084_muestras_y_placebos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="muestras_y_placebos",
            name="nombre_muestra",
            field=models.CharField(
                default=None, max_length=300, verbose_name="nombre de muestra"
            ),
            preserve_default=False,
        ),
    ]
