# Generated by Django 4.2.1 on 2023-10-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0085_muestras_y_placebos_nombre_muestra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Nombre_Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="nombre",
            field=models.CharField(max_length=250, verbose_name="Título_del_Protocolo"),
        ),
    ]
