# Generated by Django 4.2.7 on 2023-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0086_alter_parametro_nombre_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viabilidad",
            name="nombre_viabilidad",
            field=models.CharField(
                default=False, max_length=90, verbose_name="Nombre Viabilidad"
            ),
        ),
    ]
