# Generated by Django 4.2.7 on 2023-11-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0090_alter_viabilidad_nombre_viabilidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viabilidad",
            name="nombre_viabilidad",
            field=models.CharField(
                max_length=90, null=True, verbose_name="Nombre Viabilidad"
            ),
        ),
    ]
