# Generated by Django 4.2.7 on 2023-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0091_alter_viabilidad_nombre_viabilidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="muestras_y_Placebos",
            field=models.ManyToManyField(
                null=True, to="Protocolo_Metodos.muestras_y_placebos"
            ),
        ),
    ]
