# Generated by Django 4.2.7 on 2023-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0092_alter_protocolos_muestras_y_placebos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="codigo",
            field=models.CharField(
                max_length=90, null=True, verbose_name="Código Protocolo"
            ),
        ),
    ]
