# Generated by Django 4.2.7 on 2023-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0093_alter_protocolos_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="observaciones",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Observaciones"
            ),
        ),
    ]
