# Generated by Django 4.2.7 on 2023-11-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0094_alter_protocolos_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="nombre",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Título_del_Protocolo"
            ),
        ),
    ]
