# Generated by Django 4.2.7 on 2023-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0095_alter_protocolos_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                null=True, related_name="parametro", to="Protocolo_Metodos.parametro"
            ),
        ),
    ]
