# Generated by Django 4.2.7 on 2023-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0097_remove_protocolos_fecha_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="subparametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AddField(
            model_name="titulo_parametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="ensayo",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="metodologia",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="muestras_y_placebos",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
        migrations.AlterField(
            model_name="viabilidad",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
    ]
