# Generated by Django 4.2.7 on 2023-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0098_subparametro_condicion_titulo_parametro_condicion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_ingreso",
            field=models.DateField(
                help_text="AAAA/MM/DD", null=True, verbose_name="Fecha de Registro"
            ),
        ),
    ]
