# Generated by Django 4.2.7 on 2023-12-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0099_alter_protocolos_fecha_ingreso"),
    ]

    operations = [
        migrations.AddField(
            model_name="muestras_y_placebos",
            name="fecha_ingreso",
            field=models.DateField(
                help_text="AAAA/MM/DD",
                null=True,
                verbose_name="Fecha de ingreso muestra",
            ),
        ),
    ]
