# Generated by Django 4.2.7 on 2024-01-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0100_muestras_y_placebos_fecha_ingreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muestras_y_placebos",
            name="nombre_muestra",
            field=models.CharField(
                max_length=300, verbose_name="nombre de Muestra/Placebo/MP"
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Nombre Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.titulo_parametro",
                verbose_name="Titulo Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="titulo_parametro",
            name="titulo_parametro",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="Titulo Párametro"
            ),
        ),
    ]
