# Generated by Django 4.2.7 on 2024-02-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0101_alter_muestras_y_placebos_nombre_muestra_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="protocolos",
            old_name="viabilidad",
            new_name="Insumos_del_Proceso",
        ),
    ]
