# Generated by Django 4.2.7 on 2024-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0103_cliente_protocolos_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viabilidad",
            name="nombre_viabilidad",
            field=models.CharField(
                max_length=90, null=True, verbose_name="Insumos del Proceso"
            ),
        ),
    ]
