# Generated by Django 4.2.7 on 2024-02-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0104_alter_viabilidad_nombre_viabilidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametro",
            name="status_parametro",
            field=models.CharField(
                choices=[
                    ("Ingresado", "INGRESADO"),
                    ("Revisado", "REVISADO"),
                    ("Impreso", "IMPRESO"),
                    ("Auditado", "AUDITADO"),
                ],
                default="Ingresado",
                max_length=90,
                verbose_name="Progreso",
            ),
        ),
    ]
