# Generated by Django 4.2.7 on 2024-02-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0105_parametro_status_parametro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado_Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_parametro",
                    models.CharField(
                        choices=[
                            ("Registrada", "REGISTRADA"),
                            ("Revisada", "REVISADA"),
                        ],
                        default="Registrada",
                        max_length=90,
                        verbose_name="Status Parametro",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="parametro",
            name="status_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.estado_parametro",
                verbose_name="Status Parametro",
            ),
        ),
    ]
