# Generated by Django 4.2.7 on 2024-02-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0106_estado_parametro_alter_parametro_status_parametro"),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="status_parametro",),
        migrations.AddField(
            model_name="parametro",
            name="status_parametro",
            field=models.ManyToManyField(
                null=True,
                to="Protocolo_Metodos.estado_parametro",
                verbose_name="Estado Parametro",
            ),
        ),
    ]
