# Generated by Django 4.2.7 on 2024-02-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0107_remove_parametro_status_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado_parametro",
            name="status_parametro",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="Status Parametro"
            ),
        ),
        migrations.RemoveField(model_name="parametro", name="status_parametro",),
        migrations.AddField(
            model_name="parametro",
            name="status_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.estado_parametro",
                verbose_name="Estado Parametro",
            ),
        ),
    ]
