# Generated by Django 4.2.7 on 2024-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0108_alter_estado_parametro_status_parametro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametro",
            old_name="status_parametro",
            new_name="status_Parametro",
        ),
        migrations.AddField(
            model_name="estado_parametro",
            name="condicion",
            field=models.CharField(
                choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                default="Activo",
                max_length=90,
                verbose_name="Condicion",
            ),
        ),
    ]
