# Generated by Django 4.2.7 on 2024-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0109_rename_status_parametro_parametro_status_parametro_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="parametro", name="status_Parametro",),
        migrations.DeleteModel(name="Estado_Parametro",),
    ]
