# Generated by Django 4.2.7 on 2024-04-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0110_remove_parametro_status_parametro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolos",
            name="fecha_final",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Finalización"
            ),
        ),
    ]
