# Generated by Django 4.2.7 on 2024-04-18 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0111_protocolos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_final",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Fecha de Finalización",
            ),
        ),
    ]
