# Generated by Django 4.2.7 on 2024-04-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0112_alter_protocolos_fecha_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="estadoprotocolo",
            name="estado_motivo",
            field=models.CharField(
                default=None, max_length=90, verbose_name="Motivo del estado"
            ),
            preserve_default=False,
        ),
    ]
