# Generated by Django 4.2.7 on 2024-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0114_alter_estadoprotocolo_estado_motivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_motivo",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=90,
                verbose_name="Motivo del estado",
            ),
            preserve_default=False,
        ),
    ]
