# Generated by Django 4.2.7 on 2024-04-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0115_alter_estadoprotocolo_estado_motivo"),
    ]

    operations = [
        migrations.RemoveField(model_name="estadoprotocolo", name="estado_motivo",),
    ]
