# Generated by Django 4.2.7 on 2024-04-30 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0117_estadoprotocolo_estado_motivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_final",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha de Finalización",
            ),
        ),
    ]
