# Generated by Django 4.2.7 on 2024-05-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0121_alter_protocolos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_final",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Fecha de Finalización"
            ),
        ),
    ]
