# Generated by Django 4.2.7 on 2024-05-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0125_alter_protocolos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_final",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
