# Generated by Django 4.2.7 on 2024-05-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0127_alter_protocolos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre_cliente",
            field=models.CharField(
                max_length=90, null=True, unique=True, verbose_name="Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="ensayo",
            name="nombre_ensayo",
            field=models.CharField(max_length=90, unique=True, verbose_name="Ensayo"),
        ),
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_motivo",
            field=models.CharField(
                blank=True, max_length=90, unique=True, verbose_name="Motivo del estado"
            ),
        ),
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_protocolos",
            field=models.CharField(
                max_length=90, unique=True, verbose_name="Estado Protocolos"
            ),
        ),
        migrations.AlterField(
            model_name="metodologia",
            name="nombre_metodologia",
            field=models.CharField(
                max_length=90, unique=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AlterField(
            model_name="muestras_y_placebos",
            name="codigo_muestra_interno",
            field=models.CharField(
                max_length=90, unique=True, verbose_name="CIM / LIMS"
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                unique=True,
                verbose_name="Nombre Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.titulo_parametro",
                unique=True,
                verbose_name="Titulo Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="codigo",
            field=models.CharField(
                max_length=90, null=True, unique=True, verbose_name="Código Protocolo"
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="nombre",
            field=models.CharField(
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Título_del_Protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="subparametro",
            name="nombre_subparametro",
            field=models.CharField(
                blank=True, max_length=90, unique=True, verbose_name="Subparametro"
            ),
        ),
        migrations.AlterField(
            model_name="titulo_parametro",
            name="titulo_parametro",
            field=models.CharField(
                blank=True, max_length=90, unique=True, verbose_name="Titulo Párametro"
            ),
        ),
        migrations.AlterField(
            model_name="viabilidad",
            name="nombre_viabilidad",
            field=models.CharField(
                max_length=90,
                null=True,
                unique=True,
                verbose_name="Insumos del Proceso",
            ),
        ),
    ]
