# Generated by Django 4.2.7 on 2024-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0128_alter_cliente_nombre_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_motivo",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="Motivo del estado"
            ),
        ),
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_protocolos",
            field=models.CharField(max_length=90, verbose_name="Estado Protocolos"),
        ),
    ]
