# Generated by Django 4.2.7 on 2024-05-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0129_alter_estadoprotocolo_estado_motivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoprotocolo",
            name="estado_motivo",
            field=models.CharField(
                blank=True, max_length=90, unique=True, verbose_name="Motivo del estado"
            ),
        ),
    ]
