# Generated by Django 4.2.7 on 2024-05-05 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0130_alter_estadoprotocolo_estado_motivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_titulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.titulo_parametro",
                verbose_name="Titulo Parametro",
            ),
        ),
    ]
