# Generated by Django 4.2.7 on 2024-06-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0131_alter_parametro_nombre_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="nombre_parametro",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.subparametro",
                verbose_name="Nombre Parametro",
            ),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="muestras_y_Placebos",
            field=models.ManyToManyField(to="Protocolo_Metodos.muestras_y_placebos"),
        ),
        migrations.AlterField(
            model_name="protocolos",
            name="parametro",
            field=models.ManyToManyField(
                related_name="parametro", to="Protocolo_Metodos.parametro"
            ),
        ),
    ]
