# Generated by Django 4.2.7 on 2024-07-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0134_etapa_tipo_muestra_muestras_y_placebos_etapa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="etapa",
            name="ensayo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.ensayo",
                verbose_name="Ensayo",
            ),
        ),
    ]
