# Generated by Django 4.2.7 on 2024-08-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0135_etapa_ensayo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muestras_y_placebos",
            name="etapa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.etapa",
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="muestras_y_placebos",
            name="tipo_muestra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.tipo_muestra",
                verbose_name="Tipo de muestra",
            ),
        ),
    ]
