# Generated by Django 4.2.7 on 2024-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0137_alter_muestras_y_placebos_etapa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_metodo",
                    models.CharField(
                        max_length=90, unique=True, verbose_name="Método (código)"
                    ),
                ),
                (
                    "nombre_metodo",
                    models.CharField(
                        max_length=90, unique=True, verbose_name="Método (Nombre)"
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("Activo", "ACTIVO"), ("Pasivo", "PASIVO")],
                        default="Activo",
                        max_length=90,
                        verbose_name="Condicion",
                    ),
                ),
            ],
        ),
    ]
