# Generated by Django 4.2.7 on 2024-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0138_metodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolos",
            name="metodo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Protocolo_Metodos.metodo",
                verbose_name="Metodo de referencia",
            ),
        ),
    ]
